### ISSUE TITLE
Seems to break when building the image.

### ISSUE THREAD

**Issue by broodslawns** [itiligent/OpenWRT-ImageBuilder#1]
Hey there, first off, thank you so much for this. Been a nightmare trying to customize this when I'm not super strong with linux. Figured resizing a disk image would be easier, but definitely out of my wheelhouse.

So I've been trying to get an image built and keep running into the same problem. Tried to adjust the script with what I thought might've been the cause, but I think I've narrowed it down to Make stopping mid image generation and everything else fails after that.

Attaching the build.log in case you have time to take a look. Again, really appreciate your work.
[build.log](https://github.com/user-attachments/files/16008315/build.log)

**Comment by itiligent** [comment]
a few things...
Does the unedited script at its default work for you? - this is a good starting point to make sure the premise of your enviroment is ok
 
If you're playing with resize then you can get into a lot trouble trying to make SQUASH images too big. I tested up to about 4096 and then things always failed as a hard limitation - this is why I have a default at 2048.. If you need bigger , you'll have to add another EXT4 partiton UUID, then bake this new fstab into a 2nd run of of the builder to make the new partiton persistent after a reset (see the readme.)

BTW once you edit the disk size you can't use sysupgrade - you have to re-bake your own upgrade impages. Its one of those things where you gotta know how the squashfs layout,  and I struggle with this a bit too.

Also, some combos of packages wont build - try tha same combo with the openwrt online builder as see if that spits any errors as a general sanity check. 

Failing that, you'll have to show me the full edited script to see what youre trying to do and how you've changed it.

**Comment by broodslawns** [comment]
Ah yeah, to be clear, I ran the script unedited when capturing that log, except the VM portion where I commented out vmare and uncommented the QEMU build. When setting disk size, I only set 2048, nothing higher, as the extended disk space is what I’m looking to achieve. 

I didn’t try running the script without customizations through user input prompts, though. I’ll try that later when I have time and yeah, zero customizations elsewhere just to make sure it works. FYI, also using a fresh Debian build in a VM. I don’t usually use linux otherwise, just Mac.

**Comment by itiligent** [comment]
I just checked and I can run the script with its defaults just fine on Debian .  I've actually been using OWRT and this build code for many years.

Why are you editing the script? (other than for package selection). Editing the script is not required to prevent vm builds, its an option at the first prompts. - see imange. There is a bunch of things that happen at the script's  end when outputting the images or passing it on to qemu for vm conversion then cleaning up/moving about build files into somethine orderly. If you miss somthing there it will definitrly break.

What are you trying to achieve with your edits? 

![image](https://github.com/itiligent/OpenWRT-ImageBuilder/assets/94789708/92197bff-6c3d-47d8-ae07-6d6074e55bb5)

**Comment by broodslawns** [comment]
I tested earlier with no changes to the script, all defaults, and it did work. Tried again, to modify the partitions as laid out in the script prompts and used the presets provided (32 and 2048), nothing else, and it did not work. I haven't had time to get proper logs, but I will get that ouput tonight.

Per this line in the readme, "Optional conversion of new OpenWRT builds into VMware vmdk images. (edit script for qcow2, qed, vdi or vhd)" I wanted a qcow2 image conversion, so edited the script comments there only to remove vmdk as an option and generate a QEMU compatible image.

**Comment by itiligent** [comment]
I could not replicate your error and have been able to modify partitions at will (with release versions) 

I've made some minor updates to the script to make it easier
- ive changes the script defaults to OWRT's defaults and improved the on screen messages.
- I've added a new menu for selecting the type of VM conversion format (to stop any need for editing deep in the script)

If you were building a snapshot version then the previous script would have failed because it turns out OWRT recently changed the download format to .zst but annoyingly still uses tar.xz for realeases -  just to make scripting all this a real pain). This issue is now fixed but I can't test as it also looks like the current snapshot is broken on OWRT's side (this happens a bit) and I can replicate same issue manually so I reckon its not the script.

**Comment by broodslawns** [comment]
Ok, so finally got back around to this and saw that you made changes. Ran it again today, definitely improved. I think the last part you're referring to regarding the broken snapshot is why I'm seeing this output, yeah?

> ```
> make[3]: *** [Makefile:158: /home/user/Documents/openwrt-imagebuilder-23.05.3-x86-64.Linux-x86_64/build_dir/target-x86_64_musl/linux-x86_64/tmp/openwrt-23.05.3-wrt-vm-01-x86-64-generic-squashfs-rootfs.img.gz] Killed
> make[3]: *** Deleting file '/home/user/Documents/openwrt-imagebuilder-23.05.3-x86-64.Linux-x86_64/build_dir/target-x86_64_musl/linux-x86_64/tmp/openwrt-23.05.3-wrt-vm-01-x86-64-generic-squashfs-rootfs.img.gz'
> make[2]: *** [Makefile:208: build_image] Error 2
> make[1]: *** [Makefile:146: _call_image] Error 2
> make: *** [Makefile:262: image] Error 2
> /home/user/Documents/openwrt_build_output/vm/*img.gz
> gzip: /home/user/Documents/openwrt_build_output/vm/*img.gz: No such file or directory
> /home/user/Documents/openwrt_build_output/vm/*.img
> qemu-img: Could not open '/home/user/Documents/openwrt_build_output/vm/*.img': Could not open '/home/user/Documents/openwrt_build_output/vm/*.img': No such file or directory
> ```

**Comment by itiligent** [comment]
I think your issue is related to the selection of packages you are choosing and their existence/compatibiltiy with the current OWRT version you are trying to install.  (I can relplicate your error  only if I use an old package name from v22)  You have not shared your package list so I cant offer you more than that.

Look ALL through your log or on screen output for somthing like this, as this will cause it to fail.:
![image](https://github.com/itiligent/OpenWRT-ImageBuilder/assets/94789708/75b0aa73-ba3b-4b97-ac05-e3ccc294875d)

Another easy way to check for compatibiltiy is also as I mentioned earlier, to go to the online builder and choose the customize link , then try an online with your package selection just to see if it also rejects the build. 
https://firmware-selector.openwrt.org/?version=23.05.3&target=x86%2F64&id=generic

**Comment by itiligent** [comment]
I just tried the online builder - and this confirms it will give an error with the same invalid package selection... in this case its the sqm-scripts that are not part of the snapshot tree
![image](https://github.com/itiligent/OpenWRT-ImageBuilder/assets/94789708/8b397cad-35dc-4b90-a0bb-ffdbf601ac25)

**Comment by broodslawns** [comment]
Ok, that makes sense. Though I'm just running the script as is, no modifications to the package list since I was attempting to  see if it would function with the default configuration, only editing partition size and attempting to create a virtual machine image from it. Did not suspect or expect that the packages would be a problem. Let me try your suggestion and I'll be sure to look out for that and more thoroughly through the logs.

Also, thank you for the online customizer link. There's a lot to OWRT and I tend to get stuck in rabbit holes looking for stuff.

**Comment by itiligent** [comment]
I just removed some of the example packages in the script to help reduce the surface area for issues , (the idea is to clear out and strat from scratch with your own ). I think you'll find the scrip will work fine now, especially if you follow the rule of  looking up the packages you want just to make sure they are included in the version branch you want to build.
 
Also, when using the online builder you cant resize, and it adds a lot more junk in images by default that you don't usually need

**Comment by broodslawns** [comment]
Hey, thank you again. I went ahead and made an attempt before I have to do life stuff for the next two days. Unfortunately the build didn't seem to work (or it did and I'm looking at it wrong?) I've attached the build.log, editing it only to include the intial options I selected and the output of the /vm folder, just so you can see what I'm doing. I'm copying no config files of any kind to the inject folder. It's as bare bones as it can get, other than the partition resizing.

[owrtcustbld062924_10_20am.log](https://github.com/user-attachments/files/16041660/owrtcustbld062924_10_20am.log)

**Comment by broodslawns** [comment]
Oh, this is the version of Debian I'm using 

No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

**Comment by itiligent** [comment]
[](url)You should not be editing anything, and Debian 12 works fine.  (Also are you trying this on Windows susbsystem for Linux - I dont test on that) 

- Are you running the MOST CURRENT version of the script (I updated the default package examples as not all old defaults packages will work with latsest OWRT version, they are just examples to demonstrate the script's use  - I think you might be repeating the same old script code)  You have yet to confirm for me the exact pacakages you have in your script athought I've asked for this so I cant give you any more on that.

- The only place you should make a change to the script is in the CUSTOM_PACKAGES section which as I said before is where your problem lies.  **Repeat - this is where your problem lies**. 

- The idea is that you research and populate thie CUSTOM_PACKAGES section from ONLY the packages that are available in the specific OWRT verion you want. (You must Google each package name you want to use to check that it is currently included in the version you want to build as these can change.  The script is not desinged to be perfect with its example defaults as there are too many posibiliites. You have to provide input here.

- From the current script with its default packages on Debian 12 here is successful output for a snapshot build with a partion change to 64 & 1024:
![image](https://github.com/itiligent/Easy-OpenWRT-Builder/assets/94789708/1527dddf-b38d-496d-a716-204aaf869e36)
and the full [build](url) log 
I get the same output with a 23.05.3 build also and I can't fins a way to break it.  I'm not sure what else I can give you. Check the latest script and make sure you are running this.

**Comment by itiligent** [comment]
in case you are using WSL, it wont work out of the box to build images:
https://openwrt.org/docs/guide-developer/toolchain/wsl

**Comment by broodslawns** [comment]
So, again (and maybe there's some miscommunication here, correct me if I'm saying something incorrectly), there is no editing of the script being done except for what you see in the build log. There are no special packages being selected, no addition of custom configs, nothing. It's running 'straight out of the box' so to speak. I'm kinda regretting that I mentioned that I edited the script initially now because it seems it's now assumed I'm stripping stuff out or making changes to the script after the build changes you've made. I'm not.

You mention that the package list is not to be run that's in the script currently, but it's not commented out in the script and if I'm not to edit the script anyhow, it's assumed that, since there isn't instruction to the contrary, that the included packages are vetted and would run regardless of additions or no changes. So my fault for making that assumption, though I don't know how I don't edit the shell script if I'm not to make changes.

Yes, I am running the latest build change you made as of this morning, whatever build that was. I ran that script directly, unchanged. I know it was new because the new prompt during partition resizing notes not to go above 8192, which it was mentioned that 4096 was the upper limit, but I've only been setting 2048 as the partition size when advancing through the prompts. As mentioned earlier, I'm on a Mac. Debian is running as a VM in VMware Fusion on an x86 Mac. Nothing special.

So given that, I've done what you said and edited the package list in the script, in the uncommented example section, and removed everything but luci just to get some working output, and it worked.

`# Below is example only, change package list as needed.
    CUSTOM_PACKAGES="luci"`

So that appears to be where I was not understanding instructions.

**Comment by itiligent** [comment]
I'm glad you got it working. I was feeling your info was missing pieces but I've been trying. 

For all this to make more sense you may need to build a bit more of an understading about the modular architecture of OWRT and the concept of cooking up your own recipe of packages - OWRT is all about the package list.   Linux general knowleged takes time, but be open and patient and you'll get there.  

Using the word "edit" to decribe what were actually your script prompt inputs was indeed confusing. Also please understand I think you tripped yourseld up by locking in the the assumption default settings must always work - this will always lead you to dispair as Linux/OWRT is a tree with many branches and its not possile to leave exampes for every scenario that can still offer aa good description of how to format the command line with a few dozen packages. If you go back you will see that several times I was trying to lead you to the packages list.

I re-iterate: You are indeed supposed to edit JUST the **CUSTOME_PACKAGES** , this is also stated clearly in uppercase near the top of the script, and also stated directly in the readme instructions as below... Bearining in mind the target audience, I dont really know how I could add to this to make it any clearer without bloating things too much, but Im glad its working now.

1. 📥 Download the image builder script and make it executable:
   ```
   chmod +x x86-imagebuilder.sh
   ```

2. 🛠️ Customize your list of packages for inclusion in your new image under the `CUSTOM_PACKAGES` section of the script. (Packages shown in the script only examples .)

3. ▶️ Run the script as sudo and follow the setup prompts:
   ```
   sudo ./x86-imagebuilder.sh
   ```
