### ISSUE TITLE
error installing python3-distutils on Ubuntu 24.04

### ISSUE THREAD

**Issue by chas-iot** [itiligent/OpenWRT-ImageBuilder#5]
```
Package python3-distutils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-distutils' has no installation candidate
tar (child): openwrt-imagebuilder-24.10-x86-64.Linux-x86_64.tar.xz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
./x86-imagebuilder.sh: line 300: cd: /home/chas-iot/openwrt-imagebuilder-24.10-x86-64.Linux-x86_64/: No such file or directory
./x86-imagebuilder.sh: line 301: make: command not found
./x86-imagebuilder.sh: line 302: make: command not found
```
I saw some explanation of why this package is no longer available at https://stackoverflow.com/questions/78438738/how-to-install-python3-distutils-on-ubuntu-24-04

**Comment by itiligent** [comment]
Yes, if you look to https://openwrt.org/docs/guide-developer/toolchain/install-buildsystem#debianubuntumint it explains the differing dependencies since ubuntu 22 and what will work for Ubuntu 24. The solution is in the a above link.

 I have not updated the script as yet to handle this change. I will at some stage in future.

**Comment by itiligent** [comment]
I have now updated the script to choose between OpenWRT's recommended Python3.11 or  Python3.12 dependencies
